config/routes.rb
CscV2::Application.routes.draw do

  resources :generals

  get "user_info/index"

  resources :users do
    get :approve, :on=>:member
    get :profile, :on=>:member
    get :profile_edit, :on=>:member
    put :profile_update, :on=>:member
    get :change_password,:on=>:member
  end

  resources :roles do
    get :approve, :on=>:member
  end

  resources :panchayats do
    get :approve, :on=>:member
  end

  resources :blocks do
    get :approve, :on=>:member
  end

  resources :districts do
    get :approve, :on=>:member
  end

  resources :divisions do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"
  match "user_info/:id" => "user_info#index", :as=>:user_info


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  #authlogic
  acts_as_authentic do |c|
    c.require_password_confirmation= false
    c.validate_password_field= false
    c.email_field =false
    c.validate_email_field = false
  end

  #validations
  validates :name, :father_name, :dob, :gender,:presence => true, :length => {:maximum => 100}
  validates :mobile_number, :presence => true, :length => {:maximum => 10} #,:uniqueness => true
  validates :phone_number, :length => {:maximum => 11}
  validates :pin, :length => {:maximum => 6}, :presence => true

  #relations
  has_one :user_profile
  has_many :assignments
  has_many :roles, :through => :assignments

  #Attributes for User Profile
  accepts_nested_attributes_for :user_profile, :allow_destroy => true

  #Roles
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end


  #Recent and Search
  class << self
    def recent
      order('id DESC').limit(5)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
    def admin_users
      joins([:roles]).where(:roles => {:name => %w(vle district_manager district_engineer dlf_agent)})
    end
    def super_users
      joins([:roles]).where(:roles => {:name => %w(super admin manager)})
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "application", :except => [:show, :edit]
  before_filter :require_user, :recent_items
  filter_access_to :all


  def index
    @users = User.admin_users.search(params[:search]).paginate(:page => page, :per_page => per_page) if has_role?(:admin)
    @users = User.super_users.search(params[:search]).paginate(:page => page, :per_page => per_page) if has_role?(:super)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new
    @user.build_user_profile if has_role?(:admin)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    #vle code and email id generation
    district =District.find(@user.user_profile.district_id)
    district.increment!(:dis_number)
    vle_code= "BR" + district.short_code+"%04d" % district.dis_number
    @user.user_profile.vle_code= vle_code
    @user.email = @user.password = vle_code.downcase.to_s + "@vedavaagcsc.in"
    ############################################################

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  def load_divisions
    @load_divisions = Division.where(:state_id => (params[:id]) ).order("name ASC")
    respond_to do |format|
      format.js
    end
  end
  def load_districts
    @load_districts = District.where(:division_id => params[:id]).order("name ASC")
    respond_to do |format|
      format.js
    end
  end
  def load_blocks
    @load_blocks = Block.where(:district_id => (params[:id])).order("name ASC")
    respond_to do |format|
      format.js
    end

  end
  def load_panchayats
    @load_panchayats = Panchayat.where(:block_id => (params[:id])).order("name ASC")
    respond_to do |format|
      format.js
    end
  end
  def approve
    @user = User.find(params[:id])
    @user.update_attribute('status', @user.status ? false : true)
    respond_to do |format|
      format.js
    end

  end
  def profile
    @user = User.find(params[:id])
  end
  def profile_edit
    @user = current_user
  end
  def profile_update
    @user = current_user
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(profile_user_path(current_user), :notice => 'Profile Updated Successfully.') }
        format.xml { head :ok }
      else
        format.html { render :action => "profile_update" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end

  end
  def change_password

  end
  def password_change
    @user = current_user
    return flash.now[:error] = "Current password is Wrong/Blank" unless @user.valid_password? params[:old_password]
    if params[:password] == params[:password_confirmation] && !params[:password_confirmation].blank?
      @user.password = params[:password]
      if @user.save
        flash.now[:notice] = "Password Changed Successfully."
      else
        flash.now[:error]= "Password not changed"
      end
    else
      flash.now[:error] = "New Password mismatch"
      @old_password = params[:old_password]
    end

  end
  ###################################################
  private
  def recent_items
    @recent = User.recent
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@user, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name, :label => "Full Name", :placeholder => "Full Name" %>
        <%= f.input :father_name, :label => "Father Name", :placeholder => "Father Name/Husband Name" %>
        <%= f.input :gender, :collection => [:Male, :Female], :prompt => "Select Gender" %>
        <%= f.input :dob, :as => :string, :input_html => {:id => 'date_picker'}, :label => 'Date of Birth', :placeholder => "Entert Date of Birth" %>
        <%= f.input :address1, :label => "H.No", :placeholder => "House Number" %>
        <%= f.input :address2, :label => "Street/Area", :placeholder => "Street Name/Area" %>
        <%= f.input :place, :label => "Village/Town Name", :placeholder => "Village / Town Name" %>
        <%= f.input :pin, :label => "PIN", :placeholder => "PIN code Must be 6 Digits" %>
        <%= f.input :mobile_number, :label => "Mobile", :placeholder => "Mobile Number Must be 10 Digits. Ex:9885976490" %>
        <%= f.input :phone_number, :label => "Land/Alternative Phone", :placeholder => "Phone Number" %>
        <%= f.association :roles, :label_method => lambda { |role| "#{role.name.titleize} " } %>
        <%= f.simple_fields_for(:user_profile) do |up| %>
            <%= up.association :state, :collection => State.active.all(:order => 'name'), :prompt => "Choose a State", :label_method => lambda { |state| "#{state.name.titleize} " },:label=>"Select State" %>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#division').hide();

                    $('#user_user_profile_attributes_state_id').change(function () {
                        var data = $('#user_user_profile_attributes_state_id').val();
                        $.ajax({
                            type:"POST",
                            url:"load_divisions/" + data,
                            data:data
                        });
                     });
                });
            </script>
            <div id="division">
              <%= up.association :division, :collection => Division.active.all(:order => 'name'), :prompt => "Choose a Division", :label_method => lambda { |division| "#{division.name.titleize} " },:label=>"Select Division" %>
              <script type="text/javascript">
                  $(document).ready(function () {
                      $('#district').hide();

                      $('#user_user_profile_attributes_division_id').change(function () {
                          var data = $('#user_user_profile_attributes_division_id').val();
                          $.ajax({
                              type:"POST",
                              url:"load_districts/" + data,
                              data:data
                          });
                       });
                  });
               </script>
             </div>
            <div id="district">
              <%= up.association :district, :collection => District.active.all(:order => 'name'), :prompt => "Choose a District", :label_method => lambda { |district| "#{district.name.titleize} " },:label=>"Select District" %>
              <script type="text/javascript">
                  $(document).ready(function () {
                      $('#block').hide();

                      $('#user_user_profile_attributes_district_id').change(function () {
                          var data = $('#user_user_profile_attributes_district_id').val();
                          $.ajax({
                              type:"POST",
                              url:"load_blocks/" + data,
                              data:data
                          });
                       });
                  });
               </script>
             </div>
            <div id="block">
              <%= up.association :block, :collection => Block.active.all(:order => 'name'), :prompt => "Choose a Block", :label_method => lambda { |block| "#{block.name.titleize} " },:label=>"Select Block" %>
              <script type="text/javascript">
                  $(document).ready(function () {
                      $('#panchayat').hide();
                       $('#user_user_profile_attributes_block_id').change(function () {
                          var data = $('#user_user_profile_attributes_block_id').val();
                          $.ajax({
                              type:"POST",
                              url:"load_panchayats/" + data,
                              data:data
                          });
                       });
                  });
               </script>
             </div>
            <div id="panchayat">
              <%= up.association :panchayat, :collection => Panchayat.active.all(:order => 'name'), :prompt => "Choose a Panchayat", :label_method => lambda { |pan| "#{pan.name.titleize} " },:label=>"Select Panchayat" %>
             </div>
        <% end %>
         <%= f.submit 'Save', :disable_with => 'Please wait...' %>
      </fieldset>
  <% end %>
</div>
<script>
    $(function () {
        $("#date_picker").datepicker({dateFormat:'dd-mm-yy', changeMonth:true, changeYear:true, yearRange:'1900:c-18' });
    });
</script>

app/views/users/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Users</h3>
    <% if @recent.blank? %>
        No Users Added Yet...
    <% else %>
        <% for user in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to user.name, user_path(user), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%= users_path%>">
        View all Users
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/users/approve.js.erb
$("#status_<%=@user.id%>").html("<%=escape_javascript(link_to @user.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_user_path,:remote=>true)%>");

app/views/users/change_password.html.erb
<% title "VEDAVAAG | Users" %>
<h3>Users | Profile | Change Password</h3>
<div class="help_text">
  Area for Change the Password. <br/>
</div>
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= form_tag '/users/password_change', :remote => true do %>
      <fieldset>
        <table>
          <tr>
            <td><label>Current Password<em>*</em></label></td>
            <td><%= password_field_tag 'old_password', @old_password, :class => 'formTextBox tipTipRight', :title => "Enter Old Password" %></td>
          </tr>
          <tr>
            <td><label>New Password<em>*</em></label></td>
            <td><%= password_field_tag 'password', '', :class => 'formTextBox tipTipRight', :title => "Enter New Password.<br/>For more secure use combination of Characters and Numbers" %></td>
          </tr>
          <tr>
            <td><label>Confirm New Password<em>*</em></label></td>
            <td><%= password_field_tag 'password_confirmation', '', :class => 'formTextBox tipTipRight', :title => "Confirm New Password." %></td>
          </tr>
          <tr>&nbsp;</tr>
          <tr>
            <td colspan="2" align="center"><%= submit_tag 'Change Password', :class => "btnEdit" %></td>
          </tr>
        </table>
      </fieldset>
  <% end %>
  <br/>
  <%= link_to content_tag(:span, 'Back to Profile'), profile_user_path(current_user), :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Back to Home'), generals_path, :class => 'btn-blue' %>
  <br/>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% title "CSC | Users" %>
<h3>CSC | USERS | List of User's</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Users. <br/>
  Along with creating, managing Users for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New User'), new_user_path, :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Export'), "#", :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), "#", :class => 'btn-yellow' %>

</div>

<% if @users.blank? %>
    <div class="error_msg">
      OOPS!.. No Users are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @users %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Verified?</th>
        <th>Balance</th>
        <th>VLE ID</th>
        <th>Name</th>
        <th>Division</th>
        <th>District</th>
        <th>Block</th>
        <th>Panchayat</th>
        <th>Mobile</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @users.each do |user| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= user.id %>">
                <%= link_to user.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_user_path(user), :remote => true %>
              </div>
            </td>
            <td></td>
            <td><%= user.user_profile.blank? ? 'N.A' : (user.user_profile.vle_code? ? user.user_profile.vle_code : 'N.A') %>
            </td>
            <td><%= link_to highlight(user.name.titleize, params[:search]), "#", :rel => user_info_path(:id => user.id), :class => 'ajax-cluetip' %></td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.division_id? ? user.user_profile.division.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.district_id? ? user.user_profile.district.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.block_id? ? user.user_profile.block.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.panchayat_id? ? user.user_profile.panchayat.name.titleize : 'N.A') %>
            </td>
            <td><%= user.mobile_number %></td>
            <td><%= get_role(user) %></td>
            <td><%= link_to "View", user, :class => 'usuallink bold_text', :rel => "facebox" %></td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @users %> <%= will_paginate @users, :container => false %>
    </div>
<% end %>

app/views/users/load_blocks.js.erb
$('#block').show();
$('#user_user_profile_attributes_block_id').empty();
$('#user_user_profile_attributes_block_id').append($("<option></option>").attr("value","").text('Select Block'));
<% for load_block in @load_blocks %>
$('#user_user_profile_attributes_block_id').append($("<option></option>").attr("value", '<%= load_block.id %>').text('<%= load_block.name.titleize %>'));
<% end %>

app/views/users/load_divisions.js.erb
$('#division').show();
$('#user_user_profile_attributes_division_id').empty();
$('#user_user_profile_attributes_division_id').append($("<option></option>").attr("value","").text('Select Division'));
<% for division in @load_divisions %>
$('#user_user_profile_attributes_division_id').append($("<option></option>").attr("value", '<%= division.id %>').text('<%= division.name.titleize %>'));
<% end %>

app/views/users/load_panchayats.js.erb
$('#panchayat').show();
$('#user_user_profile_attributes_panchayat_id').empty();
$('#user_user_profile_attributes_panchayat_id').append($("<option></option>").attr("value","").text('Select Panchayat'));
<% for load_panchayat in @load_panchayats %>
$('#user_user_profile_attributes_panchayat_id').append($("<option></option>").attr("value", '<%= load_panchayat.id %>').text('<%= load_panchayat.name.titleize %>'));
<% end %>

app/views/users/new.html.erb
<% title "CSC | Users " %>
<h3>CSC | USERS | User Registration</h3>
<div class="help_text">
  Area for User Registration. <br/>
  A valid information should be given.<br/>
</div>
<%= render 'form',:heading => 'Create New User' %>
<div class="link_buttons">
  <%=link_to_all(users_path)%>
</div>

app/views/users/password_change.js.erb
$('#flash_messages').html('<%=escape_javascript(render :partial=>'common/flash_message')%>');

app/views/users/profile.html.erb
<% title "SECC | User" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Users | Profile | View Profile</h3>

      <div class="help_text">
        Area for Profile Details. <br/>
        User can Update their Name, Mobile Numbers Only.
      </div>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Email/Login</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th width="20%">Father Name</th>
          <td><%= @user.father_name %></td>
        </tr>
        <tr>
          <th width="20%">Date of Birth</th>
          <td><%= @user.dob? ? @user.dob.strftime("%d-%b-%Y") : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">Address</th>
          <td><%= @user.address1? ? @user.address1.titleize : '-'  %></td>
        </tr>
        <tr>
          <th width="20%">Place</th>
          <td><%= @user.place? ? @user.place.titleize : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">PIN</th>
          <td><%= @user.pin %></td>
        </tr>
        <tr>
          <th width="20%">Mobile</th>
          <td><%= @user.mobile_number %></td>
        </tr>
        <tr>
          <th width="20%">State</th>
          <td>
            <%= @user.user_profile.blank? ? 'N.A' : (@user.user_profile.state_id? ? @user.user_profile.state.name.titleize : 'N.A') %>
          </td>
        </tr>
        <tr>
          <th width="20%">Division</th>
          <td>
            <%= @user.user_profile.blank? ? 'N.A' : (@user.user_profile.division_id? ? @user.user_profile.division.name.titleize : 'N.A') %>
          </td>
        </tr>
        <tr>
          <th width="20%">District</th>
          <td>
            <%= @user.user_profile.blank? ? 'N.A' : (@user.user_profile.district_id? ? @user.user_profile.district.name.titleize : 'N.A') %>
          </td>
        </tr>
        <tr>
          <th width="20%">Block</th>
          <td>
            <%= @user.user_profile.blank? ? 'N.A' : (@user.user_profile.block_id? ? @user.user_profile.block.name.titleize : 'N.A') %>
          </td>
        </tr>
        <tr>
          <th width="20%">Panchayat</th>
          <td>
            <%= @user.user_profile.blank? ? 'N.A' : (@user.user_profile.panchayat_id? ? @user.user_profile.panchayat.name.titleize : 'N.A') %>
          </td>
        </tr>

      </table>
    </div>
  </div>
  <br/>
  <%= link_to content_tag(:span, 'Update Profile'), profile_edit_user_path(current_user), :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Change Password'), change_password_user_path(current_user), :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Back to Home'), generals_path, :class => 'btn-blue' %>
</div>

app/views/users/profile_edit.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@user, :validate => true,:url=>url_for(:action=>:profile_update)) do |f| %>
      <fieldset>
        <%= f.input :email,:label=>"Email", :disabled => true%>
        <%= f.input :name, :label=>"Name", :placeholder=>"Full Name" %>
        <%= f.input :father_name, :label=>"Father Name",:placeholder=>"Father Name" %>
        <%= f.input :gender, :collection => [:Male, :Female],:prompt=>"Select Gender" %>
        <%= f.input :dob, :label=>"DOB", :as => :date, :start_year => Date.today.year,
                    :end_year => Date.today.year - 60,
                    :order => [:day, :month, :year] %>
        <%= f.input :address1, :label=>"Address", :placeholder=>"Address" %>
        <%= f.input :address2, :label=>"Address",:placeholder=>"Address" %>
        <%= f.input :place, :label=>"Place",:placeholder=>"Village / Town Name" %>
        <%= f.input :pin, :label=>"PIN", :placeholder=>"PIN code Must be 6 Digits" %>
        <%= f.input :mobile_number, :label=>"Mobile", :placeholder=>"Mobile Number Must be 10 Digits" %>
        <%= f.input :phone_number, :label=>"Land Phone",:placeholder=>"Phone Number" %>
        <%= f.submit 'Update Profile', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
  <br/>
  <%= link_to content_tag(:span, 'Back to Profile'), profile_user_path(current_user), :class => 'btn-blue' %>
  <%# link_to content_tag(:span, 'Change Password'), change_password_user_path(current_user), :class => 'btn-blue' %>
  <br/>
</div>

app/views/users/show.html.erb
<% title "VEDAVAAG | User" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Users | View User Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Email</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th width="20%">Mobile</th>
          <td><%= @user.mobile_number %></td>
        </tr>
        <tr>
          <th width="20%">State</th>
          <td><%# @user.user_profile.state_id? ? @user.user_profile.state.name : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">District</th>
          <td><%# @user.user_profile.district_id? ? @user.user_profile.district.name : 'N.A' %></td>
        </tr>
      </table>
    </div>
  </div>
</div>