config/routes.rb
CscV2::Application.routes.draw do

  resources :generals

  get "user_info/index"

  resources :users do
    get :approve, :on=>:member
    get :profile, :on=>:member
    get :profile_edit, :on=>:member
    put :profile_update, :on=>:member
    get :change_password,:on=>:member
  end

  resources :roles do
    get :approve, :on=>:member
  end

  resources :panchayats do
    get :approve, :on=>:member
  end

  resources :blocks do
    get :approve, :on=>:member
  end

  resources :districts do
    get :approve, :on=>:member
  end

  resources :divisions do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"
  match "user_info/:id" => "user_info#index", :as=>:user_info


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/state.rb
class State < ActiveRecord::Base
  #relations
  has_many :divisions, :dependent => :destroy
  has_many :districts, :dependent => :destroy
  has_many :blocks,:dependent => :destroy
  has_many :panchayats,:dependent => :destroy


  #validations
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}
  validates :reference_code, :presence => true, :uniqueness => true, :length => {:maximum => 2}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end

    def active
      where(:status => true).order('name ASC')
    end
  end


end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_filter :recent_items
  layout "application", :except => [:show, :edit]
  def index
    @states = State.search(params[:search]).paginate(:page => page, :per_page => per_page).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @states }
    end
  end

  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @state }
    end
  end

  def edit
    @state = State.find(params[:id])
  end

  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to(states_url, :notice => 'State was successfully created.') }
        format.xml  { render :xml => @state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(states_url) }
      format.xml  { head :ok }
    end
  end
  def approve
    @state = State.find(params[:id])
    @state.update_attribute('status', @state.status ? false : true)
    respond_to do |format|
      format.js
    end
  end

  ########################################################
  private
  def recent_items
    @recent = State.recent
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@state, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:placeholder=>"Enter State Name" %>
        <%= f.input :description %>
        <%= f.input :reference_code, :label => 'Reference Name' %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/states/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent States</h3>
    <% if @recent.blank? %>
        No States Added Yet...
    <% else %>
        <% for state in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to state.name.titleize, state_path(state), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%= states_path %>">
        View all States
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/states/approve.js.erb
$("#status_<%=@state.id%>").html("<%=escape_javascript(link_to @state.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_state_path,:remote=>true)%>");

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<% title "CSC | States" %>
<h3>CSC | States | Manage States</h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing States. <br/>
  Along with creating, managing States for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New State'), new_state_path, :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Export'), "#", :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), "#", :class => 'btn-yellow' %>
</div>
<% if @states.blank? %>
    <div class="error_msg">
      OOPS!.. No States are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @states %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status?</th>
        <th>Name</th>
        <th>Reference Name</th>
        <th>Divisions</th>
        <th>Districts</th>
        <th>Blocks</th>
        <th>Panchayats</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @states.each do |state| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= state.id %>">
                <%= link_to state.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_state_path(state), :remote => true %>
              </div>
            </td>
            <td><%= highlight(state.name.titleize,params[:search]) %></td>
            <td><%= state.reference_code %></td>
            <td><%= link_to state.divisions.size, divisions_path, :class => 'tipTipRight', :title => associated_names(state.divisions) %></td>
            <td><%= link_to state.districts.size, districts_path, :class => 'tipTipRight', :title => associated_names(state.districts) %></td>
            <td><%= link_to state.blocks.size, blocks_path, :class => 'tipTipRight', :title => associated_names(state.blocks) %></td>
            <td><%= link_to state.panchayats.size, panchayats_path, :class => 'tipTipRight', :title => associated_names(state.panchayats) %></td>
            <td>
              <%= link_for_show_pop(state) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @states %> <%= will_paginate @states, :container => false %>
    </div>

<% end %>

app/views/states/new.html.erb
<% title "CSC | States " %>
<% content_for :sub_heading do %>
    <%= sub_heading('CSC | States','Create State') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New State' %>
<div class="link_buttons">
  <%=link_to_all(states_path)%>
</div>

app/views/states/show.html.erb
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>States | View State Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @state.name %></td>
        </tr>
        <tr>
          <th width="20%">Reference Name</th>
          <td><%= @state.reference_code %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @state.description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>