config/routes.rb
CscV2::Application.routes.draw do

  resources :generals

  get "user_info/index"

  resources :users do
    get :approve, :on=>:member
    get :profile, :on=>:member
    get :profile_edit, :on=>:member
    put :profile_update, :on=>:member
    get :change_password,:on=>:member
  end

  resources :roles do
    get :approve, :on=>:member
  end

  resources :panchayats do
    get :approve, :on=>:member
  end

  resources :blocks do
    get :approve, :on=>:member
  end

  resources :districts do
    get :approve, :on=>:member
  end

  resources :divisions do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"
  match "user_info/:id" => "user_info#index", :as=>:user_info


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/division.rb
class Division < ActiveRecord::Base

  #relations
  belongs_to :state
  has_many :districts, :dependent => :destroy
  has_many :blocks,:dependent => :destroy
  has_many :panchayats,:dependent => :destroy

  #validations
  validates :state_id, :presence => true
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}
  validates :short_code, :presence => true, :uniqueness => true, :length => {:maximum => 5}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        #where(:name.matches => "%#{query}%") #from meta_where gem
        joins(:state).where({:name.matches => "%#{query}%"}|{:states => [:name.matches => "%#{query}%"]})
      else
        scoped
      end
    end

    def active
      where(:status => true).order('name ASC')
    end

  end #end of class<<self

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_filter :recent_items
  layout "application", :except => [:show, :edit]

  def index
    @divisions = Division.search(params[:search]).paginate(:page => page, :per_page => per_page).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @divisions }
    end
  end

  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @division }
    end
  end

  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @division }
    end
  end

  def edit
    @division = Division.find(params[:id])
  end

  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to(divisions_url, :notice => 'Division was successfully created.') }
        format.xml  { render :xml => @division, :status => :created, :location => @division }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @division.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to(@division, :notice => 'Division was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @division.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to(divisions_url) }
      format.xml  { head :ok }
    end
  end
  def approve
    @division = Division.find(params[:id])
    @division.update_attribute('status', @division.status ? false : true)
    respond_to do |format|
      format.js
    end
  end

  ########################################################
  private
  def recent_items
    @recent = Division.recent
  end

end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@division, :validate => true) do |f| %>
      <fieldset>
        <%= f.association :state, :collection => State.active, :prompt => "Select State "%>
        <%= f.input :name,:placeholder=>"Enter Division Name" %>
        <%= f.input :description %>
        <%= f.input :short_code, :label => 'Reference Name' %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/divisions/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Divisions</h3>
    <% if @recent.blank? %>
        No Divisions Added Yet...
    <% else %>
        <% for division in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to division.name.titleize, division_path(division), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%= divisions_path %>">
        View all Divisions
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/divisions/approve.js.erb
$("#status_<%=@division.id%>").html("<%=escape_javascript(link_to @division.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_division_path,:remote=>true)%>");

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<% title "CSC | Divisions" %>
<h3>CSC | Divisions | Manage Divisons</h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Divisions. <br/>
  Along with creating, managing Divisons for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Division'), new_division_path, :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Export'), "#", :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Home'), "#", :class => 'btn-yellow' %>
</div>
<% if @divisions.blank? %>
    <div class="error_msg">
      OOPS!.. No Divisions are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @divisions %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status?</th>
        <th>Name</th>
        <th>Reference Name</th>
        <th>State</th>
        <th>Districts</th>
        <th>Blocks</th>
        <th>Panchayats</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @divisions.each do |division| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= division.id %>">
                <%= link_to division.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_division_path(division), :remote => true %>
              </div>
            </td>

            <td><%= highlight(division.name.titleize,params[:search]) %></td>
            <td><%= division.short_code %></td>
            <td><%= highlight(division.state.name.titleize,params[:search]) %></td>
            <td><%= link_to division.districts.size, districts_path, :class => 'tipTipRight', :title => associated_names(division.districts) %></td>
            <td><%= link_to division.blocks.size, blocks_path, :class => 'tipTipRight', :title => associated_names(division.blocks) %></td>
            <td><%= link_to division.panchayats.size, panchayats_path, :class => 'tipTipRight', :title => associated_names(division.panchayats) %></td>
            <td>
              <%= link_for_show_pop(division) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @divisions %> <%= will_paginate @divisions, :container => false %>
    </div>

<% end %>

app/views/divisions/new.html.erb
<% title "CSC | Divisions " %>
<% content_for :sub_heading do %>
    <%= sub_heading('CSC | Divisions','Create Division') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New Division' %>
<div class="link_buttons">
  <%=link_to_all(divisions_path)%>
</div>

app/views/divisions/show.html.erb
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Division | View Division Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @division.name %></td>
        </tr>
        <tr>
          <th width="20%">Reference Name</th>
          <td><%= @division.short_code %></td>
        </tr>
        <tr>
          <th width="20%">State</th>
          <td><%= @division.state.name %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @division.description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>