config/routes.rb
CscV2::Application.routes.draw do

  resources :generals

  get "user_info/index"

  resources :users do
    get :approve, :on=>:member
    get :profile, :on=>:member
    get :profile_edit, :on=>:member
    put :profile_update, :on=>:member
    get :change_password,:on=>:member
  end

  resources :roles do
    get :approve, :on=>:member
  end

  resources :panchayats do
    get :approve, :on=>:member
  end

  resources :blocks do
    get :approve, :on=>:member
  end

  resources :districts do
    get :approve, :on=>:member
  end

  resources :divisions do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => "user_sessions#new"
  match "user_info/:id" => "user_info#index", :as=>:user_info


  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_admin_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage Users" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_flash_message.html.erb
<div id="flash_messages">
	<% flash.each do |name, msg| %>
	<%= content_tag :div, :id => "flash_#{name}",:class =>"flash_#{name}"  do %>
	<%= msg %>
	<%= content_tag :span, :style => "float: right;" do %>
	<%= link_to_function 'close',:title=>'Close',
	:onclick => "document.getElementById('flash_#{name}').style.display='none'" %>
	<% end %>
	<% end %>
	<% end %>
</div>

app/views/common/_footer.html.erb
<div class="copyright_text">
    <div>
      © <%= Time.now.strftime('%Y') %>
  <a href="http://vedavaag.com" target="_blank" class="usuallink">Vedavaag Systems Limited </a>. This is site is optimized to Mozilla Firefox, Google Chrome and IE8+ Versions.
    </div>
</div>

app/views/common/_header.html.erb
<div id="page_top">
  <%= link_to image_tag("vedavaag_logo.jpg", :border => 0,:height => 70) %>
  <div id="top_menu">
    <div id="top_m">
      <ul class="top_menu">
        <li>Welcome-
          <%= current_user.name %>
        </li>
        <li><%= link_to 'Home', generals_path %></li>
        <li><%= link_to 'Profile', profile_user_path(current_user.id) %></li>
        <li><%= link_to "Sign out", logout_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/common/_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li>
        <%= link_to 'States', states_path,:class=>"tipTip1",:title=>"Manage States" %>
      </li>

      <li>
        <%= link_to 'Divisions', divisions_path,:class=>"tipTip1",:title=>"Manage Divisions" %>
      </li>
      <li>
        <%= link_to 'Districts', districts_path,:class=>"tipTip1",:title=>"Manage Districts" %>
      </li>
      <li>
        <%= link_to 'Blocks', blocks_path,:class=>"tipTip1",:title=>"Manage Blocks" %>
      </li>
      <li>
        <%= link_to 'Panchayats', panchayats_path,:class=>"tipTip1",:title=>"Manage Panchayats" %>
      </li>
      <li>
        <%= link_to 'Roles', roles_path,:class=>"tipTip1",:title=>"Manage Roles" %>
      </li>
      <li>
        <%= link_to 'Users', users_path,:class=>"tipTip1",:title=>"Manage Users" %>
      </li>
    </ul>
  </li>
</ul>

app/views/common/_search.html.erb
<div class="search" style="">
    <div class="margin">
        <h3>Search</h3>
        <div class="searchbox">
            <%= form_tag(controller_name, :method => 'get') do %>
             <%= hidden_field_tag :id, params[:id] %>
            <%= text_field_tag :search, params[:search], :class => "formTextBox tipTipRight",:size=>20, :title=>"Enter String to Search" %>
            <%= submit_tag 'Go', :disable_with=>'...'%>
            <% end %>
        </div>
    </div>
</div>